package com.kingak.sc.model

case class BronzeSpotifyChartData(
    id: String,
    title: String,
    rank: Int,
    date: java.time.LocalDate,
    artist: String,
    url: String,
    region: String,
    chart: String,
    trend: String,
    streams: Double,
    track_id: String,
    album: String,
    popularity: Double,
    duration_ms: Double,
    explicit: Boolean,
    release_date: java.time.LocalDate,
    available_markets: String,
    af_danceability: Double,
    af_energy: Double,
    af_key: Double,
    af_loudness: Double,
    af_mode: Double,
    af_speechiness: Double,
    af_acousticness: Double,
    af_instrumentalness: Double,
    af_liveness: Double,
    af_valence: Double,
    af_tempo: Double,
    af_time_signature: Double
)
